### ISSUE TITLE
fsr_statistics parameter descriptions are unclear

### ISSUE THREAD

**Issue by jonnew** [jetperch/jls#9]
Specifically these two:

- increment – The number of samples represented per return value.
- length – The number of return values to generate.

`increment`: does this mean the number of samples aggregated in order to calculate a statistic? Does this mean the statistics themselves are a timeseries (e.g. averages over windows in the data)? If so I think this should be stated.

`length`: Is the number of statistical results, generated from `length` windows defined by `start` and `increment`? I think a more precise explanation is warranted.

**Comment by mliberty1** [comment]
I think that you are talking about the python binding method [`Reader.fsr_statistics`](https://github.com/jetperch/jls/blob/6004156b225949520ed5646f2c5049653b743ef7/pyjls/binding.pyx#L669).  You can find more data on the underlying C function [`jls_rd_fsr_statistics`](https://github.com/jetperch/jls/blob/6004156b225949520ed5646f2c5049653b743ef7/include/jls/reader.h#L137).

When increment is 1, this function returns a single statistic, like what you see for dual markers in the UI.  When increment is larger, you get a sequence of statistics, like what you see for each pixel in a single waveform.  

I just edited the comment:

```
    def fsr_statistics(self, signal_id, start_sample_id, increment, length):
        """Read FSR statistics.

        :param signal_id: The signal id.
        :param start_sample_id: The starting sample id to read.
            The sample_id of the first recorded sample in a signal is 0.
        :param increment: The number of samples represented per return value.
        :param length: The number of return values to generate.
        :return: The 2-D array[summary][stat] of np.float32.
            * Each summary entry represents the statistics computed
              approximately over increment samples starting
              from start_sample_id + <index> * increment.
              It has length given by the length argument.
            * stat is length 4 with columns defined by SummaryFSR.

        For length 1, the return statistics are sample-accurate.
        For larger lengths, the external boundaries for index 0 (first)
        and index -1 (last) are computed exactly.  The internal boundaries
        are approximated, perfect for waveform display, but perhaps not
        suitable for other use cases.  If you need sample accurate statistics
        over multiple increments, call this function repeatedly with length 1.
        """
```

Is this clearer?

**Comment by jonnew** [comment]
Correct, I was referring to the python binding. Should have mentioned that. 

This is much clearer.  IMO,  something following text might help up in the top line definition of the function

Read FSR statistics. -> Generate statistics (mean, std, etc) of a signal over one or more temporal windows 

This is obviously just a suggestion and may be too much.

**Comment by mliberty1** [comment]
I made the documentation a little clearer in https://github.com/jetperch/jls/commit/05de0fef1c273adfcd5bba9b5023bf4d3f1075b5.  This will be in the 0.8.1 release this is building now (https://github.com/jetperch/jls/actions/runs/6226756005) and will publish to pypi when the build completes.
